In [1]:
import numpy as np

class ProblemALG004r:
    def __init__(magic, N):
        magic.N = N
    def magicsquare(n):
        magic_square = np.zeros((n.N, n.N), dtype=int)
        #a = 1
        #b, c = 0, n.N//2
        #magic_square = np.zeros((w.N,w.N), dtype=int)

        a = 1
        b, c = 0, n.N//2
        
        
        while a <= n.N**2:
            magic_square[b, c] = a
            a +=1
            newb, newc = (b-1) % n.N, (c+1) % n.N
            if magic_square[newb, newc]:
                b +=1
            else:
                b,c = newb, newc
        print(magic_square)
        
magic1 = ProblemALG004r(3)  
magic1.magicsquare()

[[8 1 6]
 [3 5 7]
 [4 9 2]]
